### ISSUE TITLE
Implement endpoints marked as TODO

### ISSUE THREAD

**Issue by mbnott** [mbnott/steen-api#2]
Many endpoints present in /routes/web.php are not implemented. Here is a list of those that should be done eventually:
- [ ] Add review - `POST /games/{id}/reviews`
- [ ] Delete review - `DELETE /games/{id}/reviews/{reviewId}`
- [ ] Delete account - `DELETE /account/{id}`
